# -*- coding: utf-8 -*-
"""Project1_(Data Preprocessing and Cleaning)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxyh0jx550-apIM1xsp9WkCehRamKb7-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/Teen_Mental_Health_Dataset.csv")

df.head()

df = pd.read_csv("/content/Teen_Mental_Health_Dataset.csv")
df = df.drop_duplicates()
null = df.isnull().sum()
df = df.drop(columns=["platform_usage", "gender"])
print("\nDataFrame head after dropping duplicates and columns:")
print(df.head())

!pip install scikit-learn
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['social_interaction_level'] = le.fit_transform(df['social_interaction_level'])

df.head()

