# -*- coding: utf-8 -*-
"""Project2_Exploratory Data Analysis (EDA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxyh0jx550-apIM1xsp9WkCehRamKb7-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/sample_data/Teen_Mental_Health_Dataset.csv")

df.head()

df = df.drop_duplicates()
null = df.isnull().sum()
df = df.drop(columns=["platform_usage", "gender"])
print("\nDataFrame head after dropping duplicates and columns:")
print(df.head())

!pip install scikit-learn
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['social_interaction_level'] = le.fit_transform(df['social_interaction_level'])

df.head()

import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/sample_data/Teen_Mental_Health_Dataset.csv")
df = df.drop_duplicates()
df = df.drop(columns=["platform_usage", "gender"])

le = LabelEncoder()
df['social_interaction_level'] = le.fit_transform(df['social_interaction_level'])

df_stats = df.describe()
display(df_stats)

"""## Understanding Trends and Outliers

To find patterns (trends) and unusual data points (outliers) in our data, we used a few visual tools:

*   **Histograms:** These charts show how often different values appear for each numerical feature, helping us see the overall spread and common ranges.

*   **Box Plots:** These plots highlight the middle range of the data and clearly mark individual data points that are far away from the rest. These isolated points are our potential outliers.

*   **Correlation Heatmap:** This colored grid shows how strongly different features move together. A bright color means they change in a similar way (positive trend), a dark color means they change in opposite ways (negative trend), and a neutral color means they don't seem related. This helps us spot relationships, for example, if more screen time is linked to higher stress.
"""

import matplotlib.pyplot as plt
import seaborn as sns

numerical_cols = ['age', 'daily_social_media_hours', 'sleep_hours',
                  'screen_time_before_sleep', 'academic_performance', 'physical_activity',
                  'stress_level', 'anxiety_level', 'addiction_level', 'depression_label']

plt.figure(figsize=(18, 15))
for i, col in enumerate(numerical_cols):
    plt.subplot(4, 3, i + 1)
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(18, 15))
for i, col in enumerate(numerical_cols):
    plt.subplot(4, 3, i + 1)
    sns.boxplot(y=df[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel(col)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 10))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""**From my analysis, here's a quick summary:**

**Distributions:** Most features, like social media use, often lean towards lower values but have some individuals with very high usage.

**Outliers:** Unusual, extreme values are present in areas like daily social media hours and screen time before sleep, indicating some teens have much higher usage than others.

**Correlations:** There are clear links between factors. For example, higher stress, anxiety, and addiction levels tend to move together. Also, less sleep might be connected to higher stress.
"""

